In [1]:
import numpy as np
x=np.array([
            [1,2],
            [3,4],
            [5,6]
            ])

w=np.array([0.5,1])

In [3]:
print(x.shape)
print(w.shape)

(3, 2)
(2,)


x is a matrix having shape (3,2). Each row represents an input vector.
w is a matrix having shape (2,). It is applied to each row of x.

In [4]:
#Manual matrix-vector multiplication
output=[]
for row in x:
    value=0
    for i in range(len(row)):
        value+=x[i]*w[i]
        output.append(value)

print(output)

[array([3.5, 5. ]), array([3.5, 5. ]), array([3.5, 5. ]), array([3.5, 5. ]), array([3.5, 5. ]), array([3.5, 5. ])]


In [7]:
print(np.dot(x,w))
print(x@w)

[2.5 5.5 8.5]
[2.5 5.5 8.5]


In [8]:
w_wrong=np.array([[0.5,1]])
print(np.dot(x,w_wrong))

ValueError: shapes (3,2) and (1,2) not aligned: 2 (dim 1) != 1 (dim 0)

In [11]:
w_col=w_wrong.reshape(-1,1)

In [13]:
print(np.dot(x,w_col))

[[2.5]
 [5.5]
 [8.5]]


Matrix multiplication requires inner dimensions to match.
(2,) is a 1D vector, while (2,1) is a column vector.
Reshaping aligns dimensions correctly.

X contains multiple input vectors as rows.
Multiplying X by w applies the same operation to every row.
This produces one output number per row at the same time.
